name: PawPaw Kim
favicon: null
layout_spectrum: 0.6096266412641853
typography_spectrum: 0.59304208913818
title: Cartomancer and Evolutionary Astrologer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafeff'
    - '#293d32'
    - '#0b140f'
    - '#b1bdc3'
    - '#5b8053'
  brandStrength: 0.5497675999067724
  lightness: 0.31632243236526847
  saturation: 0.3052509094122797
  rhythmicContrast: 0.5068332881201059
purpose: []
